// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waqrnbpjsexhaxawahem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcXJuYnBqc2V4aGF4YXdhaGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDM4MDQsImV4cCI6MjA2NzAxOTgwNH0.vm339UJCRGXyyA7Tn3z8AtsQHm_9iqRmhm5x58PQu5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});